from PySide6.QtWidgets import QWidget
from _typeshed import Incomplete
from typing import NoReturn

class CheckButton(QWidget):
    clicked: Incomplete
    def __init__(self, parent: Incomplete | None = ...) -> None: ...
    def isChecked(self): ...
    def setChecked(self, checked) -> None: ...
    def paintEvent(self, event) -> None: ...
    def mousePressEvent(self, event) -> NoReturn: ...
