from PySide6.QtCore import QRectF
from PySide6.QtGui import QPaintEvent
from typing import NoReturn
from visualchess import ChessColor as ChessColor, Piece as Piece, Square as Square
from visualchess.chesspieces import Load as Load
from workstyle import WhereMouse

class SquarePaint(WhereMouse):
    @staticmethod
    def fitSquareRect(rect: QRectF) -> QRectF: ...
    @staticmethod
    def fitSquareMarginsRect(rect: QRectF) -> QRectF: ...
    def __init__(self, *args, **kwargs) -> None: ...
    def applyMove(self) -> NoReturn: ...
    def paintEvent(self, event: QPaintEvent) -> NoReturn: ...
