from PySide6.QtGui import QPaintEvent, QPixmap
from typing import NoReturn
from visualchess import Square as Square
from workstyle import WhereMouse

class SquarePaint(WhereMouse):
    def __init__(self, *args, **kwargs) -> None: ...
    def debug(self, *_) -> NoReturn: ...
    def debug2(self, *_) -> NoReturn: ...
    def createPixMap(self) -> NoReturn: ...
    def getBoardPix(self) -> QPixmap: ...
    def paintPixMap(self) -> NoReturn: ...
    def paintEvent(self, event: QPaintEvent) -> NoReturn: ...
