from PySide6.QtCore import QRectF
from PySide6.QtGui import QPaintEvent, QResizeEvent
from _typeshed import Incomplete
from typing import NoReturn
from visualchess import File as File, Rank as Rank, chessBoardFunc as chessBoardFunc
from workstyle import WhereMouse

Labels = list[tuple[QRectF, QRectF, str]]

class StaticBoard(WhereMouse):
    hoverSquare: Incomplete
    boardSize: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def lockSize(self) -> NoReturn: ...
    def unlockSize(self) -> NoReturn: ...
    def getFile(self) -> File: ...
    def getRank(self) -> Rank: ...
    def paintEvent(self, event: QPaintEvent) -> NoReturn: ...
    def resizeEvent(self, event: QResizeEvent) -> NoReturn: ...
