from PySide6.QtWidgets import QWidget
from typing import NoReturn

class CoreWidget(QWidget):
    @staticmethod
    def parseParent(*args, **kwargs) -> QWidget: ...
    def __init__(self, *args, **kwargs) -> None: ...
    def setupWidgets(self) -> NoReturn: ...
    def setupActions(self) -> NoReturn: ...
