from PySide6.QtWidgets import *
from PySide6.QtGui import *
from PySide6.QtCore import *
from _typeshed import Incomplete

class DraggableItem(QGraphicsItem):
    rect: Incomplete
    color: Incomplete
    text: Incomplete
    def __init__(self, rect, color, text, parent: Incomplete | None = ...) -> None: ...
    def boundingRect(self): ...
    def paint(self, painter, option, widget) -> None: ...
    def mousePressEvent(self, event) -> None: ...
    def mouseMoveEvent(self, event) -> None: ...
    def mouseReleaseEvent(self, event) -> None: ...

class GraphicsView(QGraphicsView):
    def __init__(self, parent: Incomplete | None = ...) -> None: ...
    def dragEnterEvent(self, event) -> None: ...
    def dragMoveEvent(self, event) -> None: ...
    def dropEvent(self, event) -> None: ...
    def startDrag(self, item) -> None: ...

class GameWindow(QMainWindow):
    view: Incomplete
    def __init__(self, parent: Incomplete | None = ...) -> None: ...
