from PySide6.QtCore import QPoint as QPoint
from PySide6.QtWidgets import QGraphicsRectItem, QGraphicsScene
from _typeshed import Incomplete

class DraggableRectItem(QGraphicsRectItem):
    def __init__(self, x, y, width, height, color) -> None: ...
    def dragEnterEvent(self, event) -> None: ...
    def dragMoveEvent(self, event) -> None: ...
    def dropEvent(self, event) -> None: ...

class GameScene(QGraphicsScene):
    def __init__(self, parent: Incomplete | None = ...) -> None: ...
    def createGamePiece(self, x, y, width, height, color) -> None: ...
    selected_item: Incomplete
    start_pos: Incomplete
    def mousePressEvent(self, event) -> None: ...
    def mouseMoveEvent(self, event) -> None: ...
    def dragEnterEvent(self, event) -> None: ...
    def dragMoveEvent(self, event) -> None: ...
    def dropEvent(self, event) -> None: ...
