from PySide6.QtCore import QObject, QPointF
from torch import Tensor as Tensor
from typing import NoReturn

class TimePoints(QObject):
    def __init__(self, *args, **kwargs) -> None: ...
    def getLast(self) -> QPointF: ...
    def setLast(self, last: QPointF = ...) -> NoReturn: ...
    def append(self, point: QPointF) -> NoReturn: ...
