from PySide6.QtCore import QEvent, QObject as QObject
from PySide6.QtGui import QEnterEvent, QMouseEvent
from PySide6.QtWidgets import QWidget as QWidget
from _typeshed import Incomplete
from typing import NoReturn
from workstyle import CoreWidget as CoreWidget

class _WhereMouse(CoreWidget):
    click: Incomplete
    doubleClick: Incomplete
    move: Incomplete
    leave: Incomplete
    enter: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def debugger(self) -> NoReturn: ...
    def mousePressEvent(self, event) -> NoReturn: ...
    def mouseReleaseEvent(self, event) -> NoReturn: ...
    def mouseDoubleClickEvent(self, event) -> NoReturn: ...
    def mouseMoveEvent(self, event: QMouseEvent) -> NoReturn: ...
    def enterEvent(self, event: QEnterEvent) -> NoReturn: ...
    def leaveEvent(self, event: QEvent) -> NoReturn: ...

class WhereMouse(_WhereMouse): ...
