from typing import Any, Iterable

class InstanceIterationMeta(type):
    @classmethod
    def __prepare__(mcls, name: str, bases: tuple[type]) -> dict: ...
    def __init__(cls, *args, **kwargs) -> None: ...
    def __call__(cls, *args, **kwargs) -> Any: ...
    def __iter__(cls) -> Iterable: ...

class InstanceIteration(metaclass=InstanceIterationMeta): ...
